[package]
name = "testapp"
version = "0.1.0"
authors = ["Amit Aryeh Levy <amit@amitlevy.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]
path = "src/lib.rs"

[dependencies]
libt = {path = "../libt" }
